# .cargo/config.toml
[alias]
collinear = "run --bin fast_collinear -- bin/collinear_points/data/input10.txt"
rbt = "run --bin rbt_try -- bin/data/bst40.txt geo"
graph = " run --bin graph -- bin/graphs/data/digraph9.txt 5"
digraph = " run --bin digraph -- bin/graphs/data/digraph5.txt 12"
bst = "run --bin bst_trial -- bin/data/bst40.txt geo"
